version: '2'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ports:
        - 9200:9200
  fetcher:
    build: ./fetcher
    volumes:
      - ./fetcher:/app
    env_file:
      - fetcher.env
    links:
      - mongo
    restart: unless-stopped
  indexer:
    build: ./indexer
    volumes:
      - ./indexer:/app
    env_file:
      - indexer.env
    links:
      - mongo
      - elasticsearch
    restart: unless-stopped