'use strict';

module.exports = {
  DB_URL: process.env.DB_URL,
  DB_CONNECT_TIMEOUT_MS: process.env.DB_CONNECT_TIMEOUT_MS,
  ELASTIC_HOST: process.env.ELASTIC_HOST,
  ELASTIC_CONNECT_TIMEOUT_MS: process.env.ELASTIC_CONNECT_TIMEOUT_MS,
  ELASTIC_LOG_LEVEL: process.env.ELASTIC_LOG_LEVEL,
  ELASTIC_INDEX_NAME: process.env.ELASTIC_INDEX_NAME,
  INDEXER_JOB_CRON_SPEC: process.env.INDEXER_JOB_CRON_SPEC
};
