'use strict';

module.exports = {
  TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN_KEY: process.env.TWITTER_ACCESS_TOKEN_KEY,
  TWITTER_ACCESS_TOKEN_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET,
  KEYWORDS_TO_FETCH: process.env.KEYWORDS_TO_FETCH,
  DB_URL: process.env.DB_URL,
  DB_CONNECT_TIMEOUT_MS: process.env.DB_CONNECT_TIMEOUT_MS
};
